MCBooster: MCBooster::DecayMothers Struct Reference
MCBooster::DecayMothers Struct Reference
#include <DecayMothers.h>
Public Member Functions
DecayMothers (const mc_device_vector< GReal_t > &_masses, const GInt_t _ndaughters, const mc_device_vector< GReal_t > &_rnd)
__host__ __device__ GReal_t pdk (const GReal_t a, const GReal_t b, const GReal_t c) const
__host__ __device__ void bbsort (GReal_t *array, GInt_t n)
__host__ __device__ GReal_t process (const GInt_t evt, Vector4R **particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT2 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT3 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT4 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT5 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT6 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT7 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT8 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT9 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT10 &particles)
Public Attributes
const GInt_t fNDaughters
const GReal_t *__restrict__ fRandNumbers
const GReal_t *__restrict__ fMasses
Detailed Description
Definition at line 44 of file DecayMothers.h.
Constructor & Destructor Documentation
MCBooster::DecayMothers::DecayMothers (const mc_device_vector< GReal_t > & _masses, const GInt_t _ndaughters, const mc_device_vector< GReal_t > & _rnd) inline
Definition at line 52 of file DecayMothers.h.
Member Function Documentation
__host__ __device__ void MCBooster::DecayMothers::bbsort (GReal_t * array, GInt_t n) inline
Definition at line 70 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT2 & particles) inline
Definition at line 241 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT3 & particles) inline
Definition at line 248 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT4 & particles) inline
Definition at line 260 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT5 & particles) inline
Definition at line 274 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT6 & particles) inline
Definition at line 288 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT7 & particles) inline
Definition at line 303 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT8 & particles) inline
Definition at line 319 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT9 & particles) inline
Definition at line 336 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::operator() (const GInt_t evt, GT10 & particles) inline
Definition at line 354 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::pdk (const GReal_t a, const GReal_t b, const GReal_t c) const inline
Definition at line 61 of file DecayMothers.h.
__host__ __device__ GReal_t MCBooster::DecayMothers::process (const GInt_t evt, Vector4R ** particles) inline
Definition at line 93 of file DecayMothers.h.
References MCBooster::Vector4R::applyBoostTo(), MCBooster::Vector4R::d3mag(), MCBooster::Vector4R::get(), kMAXP, MCBooster::Vector4R::mass(), PI, and MCBooster::Vector4R::set().
Member Data Documentation
const GReal_t* __restrict__ MCBooster::DecayMothers::fMasses
Definition at line 49 of file DecayMothers.h.
const GInt_t MCBooster::DecayMothers::fNDaughters
Definition at line 47 of file DecayMothers.h.
const GReal_t* __restrict__ MCBooster::DecayMothers::fRandNumbers
Definition at line 48 of file DecayMothers.h.
The documentation for this struct was generated from the following file:
DecayMothers.h