MCBooster: MCBooster::Vector4R Class Reference
MCBooster::Vector4R Class Reference
#include <Vector4R.h>
Public Member Functions
__host__ __device__ Vector4R ()
__host__ __device__ Vector4R (GReal_t e, GReal_t px, GReal_t py, GReal_t pz)
__host__ __device__ Vector4R (const Vector4R &other)
__host__ __device__ void set (GInt_t i, GReal_t d)
__host__ __device__ void set (GReal_t e, GReal_t px, GReal_t py, GReal_t pz)
__host__ __device__ Vector4R & operator*= (GReal_t c)
__host__ __device__ Vector4R & operator/= (GReal_t c)
__host__ __device__ Vector4R & operator= (const Vector4R &v2)
__host__ __device__ Vector4R & operator+= (const Vector4R &v2)
__host__ __device__ Vector4R & operator-= (const Vector4R &v2)
__host__ __device__ GReal_t get (GInt_t i) const
__host__ __device__ GReal_t cont (const Vector4R &v4) const
__host__ __device__ GReal_t mass2 () const
__host__ __device__ GReal_t mass () const
__host__ __device__ void applyRotateEuler (GReal_t alpha, GReal_t beta, GReal_t gamma)
__host__ __device__ void applyBoostTo (const Vector4R &p4, bool inverse=false)
__host__ __device__ void applyBoostTo (const Vector3R &boost, bool inverse=false)
__host__ __device__ void applyBoostTo (const GReal_t bx, const GReal_t by, const GReal_t bz, bool inverse=false)
__host__ __device__ Vector4R cross (const Vector4R &v2)
__host__ __device__ GReal_t dot (const Vector4R &v2) const
__host__ __device__ GReal_t d3mag () const
__host__ __device__ GReal_t scalartripler3 (const Vector4R &p1, const Vector4R &p2, const Vector4R &p3) const
__host__ __device__ GReal_t dotr3 (const Vector4R &p1, const Vector4R &p2) const
__host__ __device__ GReal_t mag2r3 (const Vector4R &p1) const
__host__ __device__ GReal_t magr3 (const Vector4R &p1) const
Friends
__host__ __device__ friend Vector4R operator* (GReal_t d, const Vector4R &v2)
__host__ __device__ friend Vector4R operator* (const Vector4R &v2, GReal_t d)
__host__ __device__ friend Vector4R operator/ (const Vector4R &v2, GReal_t d)
__host__ __device__ friend GReal_t operator* (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ friend Vector4R operator+ (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ friend Vector4R operator- (const Vector4R &v1, const Vector4R &v2)
__host__ friend std::ostream & operator<< (std::ostream &s, const Vector4R &v)
Detailed Description
Definition at line 54 of file Vector4R.h.
Constructor & Destructor Documentation
MCBooster::Vector4R::Vector4R () inline
Definition at line 254 of file Vector4R.h.
MCBooster::Vector4R::Vector4R (GReal_t e, GReal_t px, GReal_t py, GReal_t pz) inline
Definition at line 262 of file Vector4R.h.
MCBooster::Vector4R::Vector4R (const Vector4R & other) inline
Definition at line 271 of file Vector4R.h.
References get().
Member Function Documentation
void MCBooster::Vector4R::applyBoostTo (const Vector4R & p4, bool inverse = false) inline
Definition at line 355 of file Vector4R.h.
References get().
Referenced by MCBooster::boostTo(), MCBooster::DecayMothers::process(), and MCBooster::DecayMother::process().
void MCBooster::Vector4R::applyBoostTo (const Vector3R & boost, bool inverse = false) inline
Definition at line 368 of file Vector4R.h.
References MCBooster::Vector3R::get().
void MCBooster::Vector4R::applyBoostTo (const GReal_t bx, const GReal_t by, const GReal_t bz, bool inverse = false) inline
Definition at line 430 of file Vector4R.h.
void MCBooster::Vector4R::applyRotateEuler (GReal_t alpha, GReal_t beta, GReal_t gamma) inline
Definition at line 323 of file Vector4R.h.
Referenced by MCBooster::rotateEuler().
GReal_t MCBooster::Vector4R::cont (const Vector4R & v4) const inline
Definition at line 213 of file Vector4R.h.
Vector4R MCBooster::Vector4R::cross (const Vector4R & v2) inline
Definition at line 488 of file Vector4R.h.
GReal_t MCBooster::Vector4R::d3mag () const inline
Definition at line 504 of file Vector4R.h.
Referenced by MCBooster::DecayMother::DecayMother(), and MCBooster::DecayMothers::process().
GReal_t MCBooster::Vector4R::dot (const Vector4R & v2) const inline
Definition at line 517 of file Vector4R.h.
GReal_t MCBooster::Vector4R::dotr3 (const Vector4R & p1, const Vector4R & p2) const inline
Definition at line 536 of file Vector4R.h.
References mass2().
GReal_t MCBooster::Vector4R::get (GInt_t i) const inline
Definition at line 231 of file Vector4R.h.
Referenced by applyBoostTo(), MCBooster::DecayMother::DecayMother(), MCBooster::DecayMothers::process(), MCBooster::DecayMother::process(), and Vector4R().
GReal_t MCBooster::Vector4R::mag2r3 (const Vector4R & p1) const inline
Definition at line 543 of file Vector4R.h.
References mass2().
Referenced by magr3().
GReal_t MCBooster::Vector4R::magr3 (const Vector4R & p1) const inline
Definition at line 549 of file Vector4R.h.
References mag2r3().
GReal_t MCBooster::Vector4R::mass () const inline
Definition at line 280 of file Vector4R.h.
Referenced by MCBooster::DecayMother::DecayMother(), and MCBooster::DecayMothers::process().
GReal_t MCBooster::Vector4R::mass2 () const inline
Definition at line 159 of file Vector4R.h.
Referenced by dotr3(), and mag2r3().
Vector4R & MCBooster::Vector4R::operator*= (GReal_t c) inline
Definition at line 183 of file Vector4R.h.
Vector4R & MCBooster::Vector4R::operator+= (const Vector4R & v2) inline
Definition at line 137 of file Vector4R.h.
Vector4R & MCBooster::Vector4R::operator-= (const Vector4R & v2) inline
Definition at line 148 of file Vector4R.h.
Vector4R & MCBooster::Vector4R::operator/= (GReal_t c) inline
Definition at line 194 of file Vector4R.h.
Vector4R & MCBooster::Vector4R::operator= (const Vector4R & v2) inline
Definition at line 126 of file Vector4R.h.
__host__ __device__ GReal_t MCBooster::Vector4R::scalartripler3 (const Vector4R & p1, const Vector4R & p2, const Vector4R & p3) const inline
void MCBooster::Vector4R::set (GInt_t i, GReal_t d) inline
Definition at line 236 of file Vector4R.h.
Referenced by MCBooster::DecayMothers::process(), and MCBooster::DecayMother::process().
__host__ __device__ void MCBooster::Vector4R::set (GReal_t e, GReal_t px, GReal_t py, GReal_t pz) inline
Definition at line 242 of file Vector4R.h.
Friends And Related Function Documentation
__host__ __device__ friend Vector4R operator* (GReal_t d, const Vector4R & v2) friend
Definition at line 165 of file Vector4R.h.
__host__ __device__ friend Vector4R operator* (const Vector4R & v2, GReal_t d) friend
Definition at line 171 of file Vector4R.h.
__host__ __device__ friend GReal_t operator* (const Vector4R & v1, const Vector4R & v2) friend
Definition at line 206 of file Vector4R.h.
__host__ __device__ friend Vector4R operator+ (const Vector4R & v1, const Vector4R & v2) friend
Definition at line 225 of file Vector4R.h.
__host__ __device__ friend Vector4R operator- (const Vector4R & v1, const Vector4R & v2) friend
Definition at line 219 of file Vector4R.h.
__host__ __device__ friend Vector4R operator/ (const Vector4R & v2, GReal_t d) friend
Definition at line 177 of file Vector4R.h.
__host__ friend std::ostream& operator<< (std::ostream & s, const Vector4R & v) friend
Definition at line 345 of file Vector4R.h.
The documentation for this class was generated from the following file:
Vector4R.h