MCBooster: MCBooster::DecayMother Struct Reference
MCBooster::DecayMother Struct Reference
#include <DecayMother.h>
Public Member Functions
DecayMother (const Vector4R mother, const mc_device_vector< GReal_t > &_masses, const GInt_t _ndaughters, const mc_device_vector< GReal_t > &_rnd)
__host__ __device__ GReal_t pdk (const GReal_t a, const GReal_t b, const GReal_t c) const
__host__ __device__ void bbsort (GReal_t *array, GInt_t n)
__host__ __device__ GReal_t process (const GInt_t evt, Vector4R **daugters)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT2 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT3 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT4 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT5 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT6 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT7 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT8 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT9 &particles)
__host__ __device__ GReal_t operator() (const GInt_t evt, GT10 &particles)
Public Attributes
const GInt_t fNDaughters
GReal_t fTeCmTm
GReal_t fWtMax
GReal_t fBeta0
GReal_t fBeta1
GReal_t fBeta2
const GReal_t *__restrict__ fRandNumbers
const GReal_t *__restrict__ fMasses
Detailed Description
Definition at line 43 of file DecayMother.h.
Constructor & Destructor Documentation
MCBooster::DecayMother::DecayMother (const Vector4R mother, const mc_device_vector< GReal_t > & _masses, const GInt_t _ndaughters, const mc_device_vector< GReal_t > & _rnd) inline
Definition at line 57 of file DecayMother.h.
References MCBooster::Vector4R::d3mag(), MCBooster::Vector4R::get(), and MCBooster::Vector4R::mass().
Member Function Documentation
__host__ __device__ void MCBooster::DecayMother::bbsort (GReal_t * array, GInt_t n) inline
Definition at line 112 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT2 & particles) inline
Definition at line 247 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT3 & particles) inline
Definition at line 258 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT4 & particles) inline
Definition at line 270 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT5 & particles) inline
Definition at line 284 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT6 & particles) inline
Definition at line 298 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT7 & particles) inline
Definition at line 313 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT8 & particles) inline
Definition at line 329 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT9 & particles) inline
Definition at line 346 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::operator() (const GInt_t evt, GT10 & particles) inline
Definition at line 364 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::pdk (const GReal_t a, const GReal_t b, const GReal_t c) const inline
Definition at line 103 of file DecayMother.h.
__host__ __device__ GReal_t MCBooster::DecayMother::process (const GInt_t evt, Vector4R ** daugters) inline
Definition at line 136 of file DecayMother.h.
References MCBooster::Vector4R::applyBoostTo(), MCBooster::Vector4R::get(), kMAXP, PI, and MCBooster::Vector4R::set().
Member Data Documentation
GReal_t MCBooster::DecayMother::fBeta0
Definition at line 49 of file DecayMother.h.
GReal_t MCBooster::DecayMother::fBeta1
Definition at line 50 of file DecayMother.h.
GReal_t MCBooster::DecayMother::fBeta2
Definition at line 51 of file DecayMother.h.
const GReal_t* __restrict__ MCBooster::DecayMother::fMasses
Definition at line 54 of file DecayMother.h.
const GInt_t MCBooster::DecayMother::fNDaughters
Definition at line 46 of file DecayMother.h.
const GReal_t* __restrict__ MCBooster::DecayMother::fRandNumbers
Definition at line 53 of file DecayMother.h.
GReal_t MCBooster::DecayMother::fTeCmTm
Definition at line 47 of file DecayMother.h.
GReal_t MCBooster::DecayMother::fWtMax
Definition at line 48 of file DecayMother.h.
The documentation for this struct was generated from the following file:
DecayMother.h