MCBooster: MCBooster::Vector3R Class Reference
MCBooster::Vector3R Class Reference
#include <Vector3R.h>
Public Member Functions
__host__ __device__ Vector3R ()
__host__ __device__ Vector3R (GReal_t x, GReal_t y, GReal_t z)
__host__ __device__ Vector3R (const Vector3R &other)
__host__ __device__ Vector3R & operator*= (const GReal_t c)
__host__ __device__ Vector3R & operator/= (const GReal_t c)
__host__ __device__ Vector3R & operator+= (const Vector3R &v2)
__host__ __device__ Vector3R & operator-= (const Vector3R &v2)
__host__ __device__ void set (GInt_t i, GReal_t d)
__host__ __device__ void set (GReal_t x, GReal_t y, GReal_t z)
__host__ __device__ void applyRotateEuler (GReal_t phi, GReal_t theta, GReal_t ksi)
__host__ __device__ GReal_t get (GInt_t i) const
__host__ __device__ GReal_t dot (const Vector3R &v2)
__host__ __device__ GReal_t d3mag () const
Friends
__host__ __device__ friend Vector3R rotateEuler (const Vector3R &v, GReal_t phi, GReal_t theta, GReal_t ksi)
__host__ __device__ friend Vector3R operator* (GReal_t c, const Vector3R &v2)
__host__ __device__ friend GReal_t operator* (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator+ (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator- (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator* (const Vector3R &v1, GReal_t c)
__host__ __device__ friend Vector3R operator/ (const Vector3R &v1, GReal_t c)
__host__ __device__ friend Vector3R cross (const Vector3R &v1, const Vector3R &v2)
__host__ friend std::ostream & operator<< (std::ostream &s, const Vector3R &v)
Detailed Description
Definition at line 41 of file Vector3R.h.
Constructor & Destructor Documentation
MCBooster::Vector3R::Vector3R () inline
Definition at line 178 of file Vector3R.h.
MCBooster::Vector3R::Vector3R (GReal_t x, GReal_t y, GReal_t z) inline
Definition at line 184 of file Vector3R.h.
MCBooster::Vector3R::Vector3R (const Vector3R & other) inline
Definition at line 192 of file Vector3R.h.
References get().
Member Function Documentation
void MCBooster::Vector3R::applyRotateEuler (GReal_t phi, GReal_t theta, GReal_t ksi) inline
Definition at line 210 of file Vector3R.h.
Referenced by MCBooster::rotateEuler().
GReal_t MCBooster::Vector3R::d3mag () const inline
Definition at line 255 of file Vector3R.h.
GReal_t MCBooster::Vector3R::dot (const Vector3R & v2) inline
Definition at line 267 of file Vector3R.h.
GReal_t MCBooster::Vector3R::get (GInt_t i) const inline
Definition at line 159 of file Vector3R.h.
Referenced by MCBooster::Vector4R::applyBoostTo(), and Vector3R().
Vector3R & MCBooster::Vector3R::operator*= (const GReal_t c) inline
Definition at line 86 of file Vector3R.h.
Vector3R & MCBooster::Vector3R::operator+= (const Vector3R & v2) inline
Definition at line 104 of file Vector3R.h.
Vector3R & MCBooster::Vector3R::operator-= (const Vector3R & v2) inline
Definition at line 113 of file Vector3R.h.
Vector3R & MCBooster::Vector3R::operator/= (const GReal_t c) inline
Definition at line 95 of file Vector3R.h.
void MCBooster::Vector3R::set (GInt_t i, GReal_t d) inline
Definition at line 164 of file Vector3R.h.
void MCBooster::Vector3R::set (GReal_t x, GReal_t y, GReal_t z) inline
Definition at line 170 of file Vector3R.h.
Friends And Related Function Documentation
__host__ __device__ friend Vector3R cross (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 243 of file Vector3R.h.
__host__ __device__ friend Vector3R operator* (GReal_t c, const Vector3R & v2) friend
Definition at line 122 of file Vector3R.h.
__host__ __device__ friend GReal_t operator* (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 140 of file Vector3R.h.
__host__ __device__ friend Vector3R operator* (const Vector3R & v1, GReal_t c) friend
Definition at line 128 of file Vector3R.h.
__host__ __device__ friend Vector3R operator+ (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 146 of file Vector3R.h.
__host__ __device__ friend Vector3R operator- (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 152 of file Vector3R.h.
__host__ __device__ friend Vector3R operator/ (const Vector3R & v1, GReal_t c) friend
Definition at line 134 of file Vector3R.h.
__host__ friend std::ostream& operator<< (std::ostream & s, const Vector3R & v) friend
Definition at line 234 of file Vector3R.h.
__host__ __device__ friend Vector3R rotateEuler (const Vector3R & v, GReal_t phi, GReal_t theta, GReal_t ksi) friend
Definition at line 200 of file Vector3R.h.
The documentation for this class was generated from the following file:
Vector3R.h