MCBooster: MCBooster Namespace Reference
MCBooster Namespace Reference
Classes
struct Calculate
struct Calculate2
struct Calculate3
struct DecayMother
struct DecayMothers
struct Events
Events is a container struct to hold all the information corresponding the generated events.
struct FlagAcceptReject
Flags generated events as accepted (1) or rejected (0).
struct IFunction
IFunction is the base class for arbitrary functions return any type suported by the framwork.
struct IFunctionArray
class PhaseSpace
Implementation of the event generator.
struct RandGen
Fill a given vector with random numbers between 0 and 1.
class Vector3R
class Vector4R
Typedefs
template<typename T >
using mc_device_vector = thrust::host_vector< T >
Generic template typedef for thrust::host_vector.
template<typename T >
using mc_host_vector = thrust::host_vector< T >
Generic template typedef for thrust::host_vector.
typedef thrust::complex< GReal_t > GComplex_t
typedef mc_host_vector< Vector4R > FourVectors_h
Typedef for complex number.
typedef mc_host_vector< Vector3R > ThreeVectors_h
Vector4R host vector.
typedef mc_host_vector< GBool_t > BoolVector_h
Vector3R host vector.
typedef mc_host_vector< GReal_t > RealVector_h
Typedef for a GBool_t host vector.
typedef mc_host_vector< GComplex_t > ComplexVector_h
Typedef for a GReal_t host vector.
typedef mc_host_vector< Vector4R > Particles_h
Typedef for a GComplex_t host vector.
typedef vector< Particles_h * > ParticlesSet_h
Typedef for a Vector4R host vector.
typedef vector< RealVector_h * > VariableSet_h
Typedef for a STL vector of pointers to host Particles_h vectors .
typedef mc_device_vector< GBool_t > BoolVector_d
Typedef for a STL vector of pointers to host RealVector_h vectors.
typedef mc_device_vector< GReal_t > RealVector_d
Typedef for a GBool_t device vector.
typedef mc_device_vector< GComplex_t > ComplexVector_d
Typedef for a GReal_t device vector.
typedef mc_device_vector< Vector4R > Particles_d
Typedef for a GComplex_t device vector.
typedef vector< Particles_d * > ParticlesSet_d
Typedef for a Vector4R device vector.
typedef vector< RealVector_d * > VariableSet_d
Typedef for a STL vector of pointers to device Particles_d vectors.
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GT1
Typedef for a STL vector of pointers to device RealVector_d vectors.
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GT2
GT2 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GT3
GT3 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GT4
GT4 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &,...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GT5
GT5 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &,...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GT6
GT6 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &,Vector4R &,...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type > GT7
GT7 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &,Vector4R &,Vector4R &,...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type > GT8
GT8 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &,Vector4R &,Vector4R &,Vector4R &,...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type > GT9
GT9 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &,Vector4R &,Vector4R &,Vector4R &,Vector4R &...>
typedef thrust::detail::tuple_of_iterator_references< Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R & > GT10
GT10 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &,Vector4R &,Vector4R &,Vector4R &,Vector4R &,Vector4R &>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GTR2
GTR2 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GTR3
GTR3 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GTR4
GTR4 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GTR5
GTR5 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type > GTR6
GTR6 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type > GTR7
GTR7 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type > GTR8
GTR8 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type > GTR9
GTR9 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef thrust::detail::tuple_of_iterator_references< GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R & > GTR10
GTR10 iterator is a typedef for thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, ...>
typedef char GChar_t
Signed Character 1 byte (char)
typedef unsigned char GUChar_t
Unsigned Character 1 byte (unsigned char)
typedef short GShort_t
Signed Short integer 2 bytes (short)
typedef unsigned short GUShort_t
Unsigned Short integer 2 bytes (unsigned short)
typedef int GInt_t
Signed integer 4 bytes (int)
typedef unsigned int GUInt_t
Unsigned integer 4 bytes (unsigned int)
typedef long GLong_t
Signed long integer 4 bytes (long)
typedef unsigned long GULong_t
typedef float GFloat_t
Float 4 bytes (float)
typedef double GDouble_t
Double 8 bytes.
typedef long double GLongDouble_t
Long Double.
typedef char GText_t
General string (char)
typedef bool GBool_t
Boolean (0=false, 1=true) (bool)
typedef unsigned char GByte_t
Byte (8 bits) (unsigned char)
typedef long long GLong64_t
Portable signed long integer 8 bytes.
typedef unsigned long long GULong64_t
Portable unsigned long integer 8 bytes.
typedef double GReal_t
Double 8 bytes or float 4 bytes.
Functions
template<typename CUSTOMFUNC , typename RESULT >
void Evaluate (const CUSTOMFUNC funcObj, ParticlesSet_d &pset, mc_host_vector< RESULT > &eval)
Template functor for evaluate an arbitrary function object.
template<typename CUSTOMFUNC , typename RESULT >
void Evaluate (const CUSTOMFUNC funcObj, ParticlesSet_d &pset, mc_device_vector< RESULT > dev_out)
Template functor for evaluate an arbitrary function object.
template<typename CUSTOMFUNC >
void Evaluate (const CUSTOMFUNC funcObj, ParticlesSet_d &pset)
Template functor for evaluate an arbitrary function object.
template<typename CUSTOMFUNC >
void EvaluateArray (const CUSTOMFUNC funcObj, ParticlesSet_d &pset, VariableSet_h &varset)
Template functor for calculate an array of variables over a given set of particles.
timespec time_diff (timespec start, timespec end)
Function to calculate time intervals in seconds.
Vector3R operator* (GReal_t c, const Vector3R &v2)
Vector3R operator* (const Vector3R &v1, GReal_t c)
Vector3R operator/ (const Vector3R &v1, GReal_t c)
GReal_t operator* (const Vector3R &v1, const Vector3R &v2)
Vector3R operator+ (const Vector3R &v1, const Vector3R &v2)
Vector3R operator- (const Vector3R &v1, const Vector3R &v2)
Vector3R rotateEuler (const Vector3R &v, GReal_t alpha, GReal_t beta, GReal_t gamma)
ostream & operator<< (ostream &s, const Vector3R &v)
Vector3R cross (const Vector3R &p1, const Vector3R &p2)
Vector4R rotateEuler (const Vector4R &rs, GReal_t alpha, GReal_t beta, GReal_t gamma)
Vector4R boostTo (const Vector4R &rs, const Vector4R &p4, bool inverse=false)
Vector4R boostTo (const Vector4R &rs, const Vector3R &boost, bool inverse=false)
Vector4R operator* (GReal_t c, const Vector4R &v2)
Vector4R operator* (const Vector4R &v2, GReal_t c)
Vector4R operator/ (const Vector4R &v2, GReal_t c)
GReal_t operator* (const Vector4R &v1, const Vector4R &v2)
Vector4R operator- (const Vector4R &v1, const Vector4R &v2)
Vector4R operator+ (const Vector4R &v1, const Vector4R &v2)
ostream & operator<< (ostream &s, const Vector4R &v)
Variables
const GBool_t kTrue = true
const GBool_t kFalse = false
Typedef Documentation
typedef mc_device_vector<GBool_t> MCBooster::BoolVector_d
Definition at line 112 of file GContainers.h.
typedef mc_host_vector<GBool_t> MCBooster::BoolVector_h
Use it to store four-vectors at host.
Definition at line 102 of file GContainers.h.
typedef mc_device_vector<GComplex_t> MCBooster::ComplexVector_d
Definition at line 114 of file GContainers.h.
typedef mc_host_vector<GComplex_t> MCBooster::ComplexVector_h
Definition at line 104 of file GContainers.h.
typedef mc_host_vector<Vector4R> MCBooster::FourVectors_h
Definition at line 96 of file GContainers.h.
typedef bool MCBooster::GBool_t
Definition at line 45 of file GTypes.h.
typedef unsigned char MCBooster::GByte_t
Definition at line 46 of file GTypes.h.
typedef char MCBooster::GChar_t
Definition at line 33 of file GTypes.h.
typedef thrust::complex<GReal_t> MCBooster::GComplex_t
Definition at line 92 of file GContainers.h.
typedef double MCBooster::GDouble_t
Definition at line 42 of file GTypes.h.
typedef float MCBooster::GFloat_t
Definition at line 41 of file GTypes.h.
typedef int MCBooster::GInt_t
Definition at line 37 of file GTypes.h.
typedef long long MCBooster::GLong64_t
Definition at line 47 of file GTypes.h.
typedef long MCBooster::GLong_t
Definition at line 39 of file GTypes.h.
typedef long double MCBooster::GLongDouble_t
Definition at line 43 of file GTypes.h.
typedef double MCBooster::GReal_t
Definition at line 52 of file GTypes.h.
typedef short MCBooster::GShort_t
Definition at line 35 of file GTypes.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT1
GT1 iterator is a typedef for thrust::detail::tuple_of_iterator_references<Vector4R &,...>
Definition at line 124 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &> MCBooster::GT10
Definition at line 175 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT2
Definition at line 130 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT3
Definition at line 136 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT4
Definition at line 142 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT5
Definition at line 148 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT6
Definition at line 154 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GT7
Definition at line 159 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type> MCBooster::GT8
Definition at line 164 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type> MCBooster::GT9
Definition at line 170 of file GContainers.h.
typedef char MCBooster::GText_t
Definition at line 44 of file GTypes.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &> MCBooster::GTR10
Definition at line 235 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GTR2
Definition at line 184 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GTR3
Definition at line 193 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GTR4
Definition at line 202 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GTR5
Definition at line 210 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GTR6
Definition at line 215 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type, thrust::null_type> MCBooster::GTR7
Definition at line 220 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type, thrust::null_type> MCBooster::GTR8
Definition at line 225 of file GContainers.h.
typedef thrust::detail::tuple_of_iterator_references<GReal_t &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, Vector4R &, thrust::null_type> MCBooster::GTR9
Definition at line 230 of file GContainers.h.
typedef unsigned char MCBooster::GUChar_t
Definition at line 34 of file GTypes.h.
typedef unsigned int MCBooster::GUInt_t
Definition at line 38 of file GTypes.h.
typedef unsigned long long MCBooster::GULong64_t
Definition at line 48 of file GTypes.h.
typedef unsigned long MCBooster::GULong_t
Definition at line 40 of file GTypes.h.
typedef unsigned short MCBooster::GUShort_t
Definition at line 36 of file GTypes.h.
template<typename T > using MCBooster::mc_device_vector = typedef thrust::host_vector<T>
Use it instead of Thrust implementation in order to avoid problems to compile OpenMP based applications using gcc and without a cuda runtime installation.
Definition at line 60 of file GContainers.h.
template<typename T > using MCBooster::mc_host_vector = typedef thrust::host_vector<T>
Use it instead of Thrust implementation in order to avoid problems to compile OpenMP based applications using gcc and without a cuda runtime installation. mc_host_vectot will always allocate page locked memory on CUDA backends in order to maximize speed in memory transfers to the device.
Definition at line 68 of file GContainers.h.
typedef mc_device_vector<Vector4R> MCBooster::Particles_d
Definition at line 115 of file GContainers.h.
typedef mc_host_vector<Vector4R> MCBooster::Particles_h
Definition at line 105 of file GContainers.h.
typedef vector<Particles_d*> MCBooster::ParticlesSet_d
Definition at line 116 of file GContainers.h.
typedef vector<Particles_h*> MCBooster::ParticlesSet_h
Definition at line 106 of file GContainers.h.
typedef mc_device_vector<GReal_t> MCBooster::RealVector_d
Definition at line 113 of file GContainers.h.
typedef mc_host_vector<GReal_t> MCBooster::RealVector_h
Definition at line 103 of file GContainers.h.
typedef mc_host_vector<Vector3R> MCBooster::ThreeVectors_h
Use it to store four-vectors at host.
Definition at line 97 of file GContainers.h.
typedef vector<RealVector_d*> MCBooster::VariableSet_d
Definition at line 117 of file GContainers.h.
typedef vector<RealVector_h*> MCBooster::VariableSet_h
Definition at line 107 of file GContainers.h.
Function Documentation
Vector4R MCBooster::boostTo (const Vector4R & rs, const Vector4R & p4, bool inverse = false) inline
Definition at line 305 of file Vector4R.h.
References MCBooster::Vector4R::applyBoostTo().
Vector4R MCBooster::boostTo (const Vector4R & rs, const Vector3R & boost, bool inverse = false) inline
Definition at line 314 of file Vector4R.h.
References MCBooster::Vector4R::applyBoostTo().
Vector3R MCBooster::cross (const Vector3R & p1, const Vector3R & p2) inline
Definition at line 243 of file Vector3R.h.
template<typename CUSTOMFUNC , typename RESULT > void MCBooster::Evaluate (const CUSTOMFUNC funcObj, ParticlesSet_d & pset, mc_host_vector< RESULT > & eval)
Template functor for evaluate an arbitrary function object over the a set of particles stored in the device. Results are returned to the host via a given mc_host_vector. Datasets with up to nine particles can be handled.
Definition at line 50 of file Evaluate.h.
template<typename CUSTOMFUNC , typename RESULT > void MCBooster::Evaluate (const CUSTOMFUNC funcObj, ParticlesSet_d & pset, mc_device_vector< RESULT > dev_out)
Template functor for evaluate an arbitrary function object over the a set of particles stored in the device. Results are returned to the device via a given mc_device_vector. Datasets with up to nine particles can be handled.
Definition at line 280 of file Evaluate.h.
template<typename CUSTOMFUNC > void MCBooster::Evaluate (const CUSTOMFUNC funcObj, ParticlesSet_d & pset)
Template functor for evaluate an arbitrary function object over the a set of particles stored in the device. No results are returned. This function is used to modify the particles in the input dataset. Datasets with up to nine particles can be handled.
Definition at line 506 of file Evaluate.h.
template<typename CUSTOMFUNC > void MCBooster::EvaluateArray (const CUSTOMFUNC funcObj, ParticlesSet_d & pset, VariableSet_h & varset)
Template functor for evaluate an arbitrary function object over the a set of particles stored in the device. The function is supposed to evaluate at once many variables and the results are returned to the host via a given VariableSet_h. Datasets with up to nine particles can be handled.
Definition at line 51 of file EvaluateArray.h.
Vector3R MCBooster::operator* (GReal_t c, const Vector3R & v2) inline
Definition at line 122 of file Vector3R.h.
Vector3R MCBooster::operator* (const Vector3R & v1, GReal_t c) inline
Definition at line 128 of file Vector3R.h.
GReal_t MCBooster::operator* (const Vector3R & v1, const Vector3R & v2) inline
Definition at line 140 of file Vector3R.h.
Vector4R MCBooster::operator* (GReal_t c, const Vector4R & v2) inline
Definition at line 165 of file Vector4R.h.
Vector4R MCBooster::operator* (const Vector4R & v2, GReal_t c) inline
Definition at line 171 of file Vector4R.h.
GReal_t MCBooster::operator* (const Vector4R & v1, const Vector4R & v2) inline
Definition at line 206 of file Vector4R.h.
Vector3R MCBooster::operator+ (const Vector3R & v1, const Vector3R & v2) inline
Definition at line 146 of file Vector3R.h.
Vector4R MCBooster::operator+ (const Vector4R & v1, const Vector4R & v2) inline
Definition at line 225 of file Vector4R.h.
Vector3R MCBooster::operator- (const Vector3R & v1, const Vector3R & v2) inline
Definition at line 152 of file Vector3R.h.
Vector4R MCBooster::operator- (const Vector4R & v1, const Vector4R & v2) inline
Definition at line 219 of file Vector4R.h.
Vector3R MCBooster::operator/ (const Vector3R & v1, GReal_t c) inline
Definition at line 134 of file Vector3R.h.
Vector4R MCBooster::operator/ (const Vector4R & v2, GReal_t c) inline
Definition at line 177 of file Vector4R.h.
ostream& MCBooster::operator<< (std::ostream & s, const Vector3R & v) inline
Definition at line 234 of file Vector3R.h.
ostream& MCBooster::operator<< (std::ostream & s, const Vector4R & v) inline
Definition at line 345 of file Vector4R.h.
Vector4R MCBooster::rotateEuler (const Vector4R & rs, GReal_t alpha, GReal_t beta, GReal_t gamma) inline
Definition at line 295 of file Vector4R.h.
References MCBooster::Vector4R::applyRotateEuler().
Vector3R MCBooster::rotateEuler (const Vector3R & v, GReal_t alpha, GReal_t beta, GReal_t gamma) inline
Definition at line 200 of file Vector3R.h.
References MCBooster::Vector3R::applyRotateEuler().
timespec MCBooster::time_diff (timespec start, timespec end)
Definition at line 88 of file Generate.h.
Referenced by MCBooster::PhaseSpace::Generate().
Variable Documentation
const GBool_t MCBooster::kFalse = false
Definition at line 62 of file GTypes.h.
const GBool_t MCBooster::kTrue = true
Definition at line 61 of file GTypes.h.
Referenced by MCBooster::PhaseSpace::Unweight().